<template>
  <div class="home">
    <h1>Welcome to Your Vue.js App</h1>
    <p>This is a template generated by Dyad AI App Builder</p>
  </div>
</template>

<script>
export default {
  name: 'HomeView'
}
</script>

<style scoped>
.home {
  padding: 20px;
}
</style>